version: '3.1'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./fiberlux/flex-o:/mnt/flex-o
      - ./fiberlux/flex-o/l10n-cpe:/mnt/l10n-cpe
      - ./fiberlux/itgrupo:/mnt/itgrupo
      - ./fiberlux/payroll_it:/mnt/payroll_it
      - ./fiberlux/extras:/mnt/extras
      - ./fiberlux/noenterprise:/mnt/noenterprise
      - ./fiberlux/usefull_modules:/mnt/usefull_modules
      - ./fiberlux/reports:/mnt/reports

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
